### ISSUE TITLE
`.editorconfig`

### ISSUE THREAD

**Issue by just-ero** [ZacharyPatten/dotnet-console-games#71]
Since this repository is meant to help C# beginners setting foot in the programming world, I think it would be good to show some best practices and enforce them for contributors.

Currently, the `.editorconfig` file in the root directory is not even part of the solution. I'm not sure Visual Studio (or other IDEs) pick up on its rules as it stands.

I'm suggesting adding all .NET- and C#-specific rules and enforcing them in a way which is closest to the .NET standard. This way, new coders will learn good convention the moment they set foot into this repository. I'm happy to do this myself (I already have a complete `.editorconfig` file lying around).

**Comment by ZacharyPatten** [comment]
Hey @just-ero, sorry for the very delayed replay. Was very busy at the end of 2022.

The current location of the `.editorconfig` file is intentional. Just because you can't see it when you open it in Visual Studio doesn't mean it isn't in effect. Also, you switch to "folder view" in Visual Studio and you can easily see the file. There isn't a need to reference it in the solution files.
